### ISSUE TITLE
Is it possible to evaluate a method without Docker?

### ISSUE THREAD

**Issue by Kiode** [p-lambda/swords#1]

**Comment by minggg** [comment]
Hi Kiode,

Thanks for your interest in Swords!  We will add instructions on how to run the evaluation outside of Docker this weekend.

Sincerely,
Mina

**Comment by chrisdonahue** [comment]
Hi @Kiode 

Apologies for the delay! We have added instructions to the README for running the evaluation script without Docker: https://github.com/p-lambda/swords#without-docker

We still highly recommend the use of Docker (especially for published results) as it ensures comparable numbers, but hopefully these instructions suffice for development purposes.
